### ISSUE TITLE
[buildcff2vf] requires off-curve compatibility: should provide error message without stack dump

### ISSUE THREAD

**Issue by frankrolf** [adobe-type-tools/afdko#1003]
I am experiencing that building CFF2 variable fonts requires off-curve point compatibility, which I did not expect to be the case.

I build the attached test case like this:
```
buildmasterotfs -d VarTest.designspace
... (works)
buildcff2vf -d VarTest.designspace

Reading source fonts...
Building VF font...
Traceback (most recent call last):
  File "/usr/local/bin/buildcff2vf", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/afdko/buildcff2vf.py", line 473, in main
    varFont, _, _ = varLib.build(designspace, otfFinder)
  File "/usr/local/lib/python3.7/site-packages/fontTools/varLib/__init__.py", line 872, in build
    _add_CFF2(vf, model, master_fonts)
  File "/usr/local/lib/python3.7/site-packages/fontTools/varLib/__init__.py", line 676, in _add_CFF2
    merge_region_fonts(varFont, model, ordered_fonts_list, glyphOrder)
  File "/usr/local/lib/python3.7/site-packages/fontTools/varLib/cff.py", line 319, in merge_region_fonts
    cvData = merge_charstrings(glyphOrder, num_masters, top_dicts, model)
  File "/usr/local/lib/python3.7/site-packages/fontTools/varLib/cff.py", line 375, in merge_charstrings
    region_charstring.draw(var_pen)
  File "/usr/local/lib/python3.7/site-packages/fontTools/misc/psCharStrings.py", line 982, in draw
    extractor.execute(self)
  File "/usr/local/lib/python3.7/site-packages/fontTools/misc/psCharStrings.py", line 299, in execute
    rv = handler(index)
  File "/usr/local/lib/python3.7/site-packages/fontTools/misc/psCharStrings.py", line 590, in op_rlineto
    self.rLineTo(point)
  File "/usr/local/lib/python3.7/site-packages/fontTools/misc/psCharStrings.py", line 524, in rLineTo
    self.pen.lineTo(self._nextPoint(point))
  File "/usr/local/lib/python3.7/site-packages/fontTools/pens/basePen.py", line 254, in lineTo
    self._lineTo(pt)
  File "/usr/local/lib/python3.7/site-packages/fontTools/varLib/cff.py", line 585, in _lineTo
    self.add_point('rlineto', pt_coords)
  File "/usr/local/lib/python3.7/site-packages/fontTools/varLib/cff.py", line 541, in add_point
    cmd[0], self.glyphName)
fontTools.varLib.cff.MergeTypeError: In glyph 'a' 'rlineto' at point index 2 in master index 1 differs from the default font point type 'rrcurveto'
```

[VarTest.zip](https://github.com/adobe-type-tools/afdko/files/3736644/VarTest.zip)

**Comment by readroberts** [comment]
Hi Frank;

Checking and fixing this kind of compatibility issue by buildcff2vf takes some time, so it is not done by default. If you encounter this kind of problem, run buildcff2vf again, but add the option ‘-c’.


  *   Read

**Comment by frankrolf** [comment]
Thanks! 
If at all possible, it might be useful to make the user aware of this option before (or after) failing?

**Comment by readroberts** [comment]
Certainly.  I thought that buildcff2vf already failed gracefully, without a stack dump as you saw, and with advice to supply the "-c" option. your experience is definitely a bug. I will change the issue title accordingly.

**Comment by josh-hadley** [comment]
I intend to just trap for `varLib.cff.MergeTypeError` (specifically) on the line
> `varFont, _, _ = varLib.build(designspace, otfFinder)`

...then issue an error message, something like "The input set requires compatibilization. Please try again with the -c (--check-compat) option." (unless some other wording is preferred) then return with exit code 0. I'll also add this case to the test suite, if that's okay.
