### ISSUE TITLE
[ProofPDF.py] Traceback in addComponent from fontTools\pens\basePen.py

### ISSUE THREAD

**Issue by Arno-Enslin** [adobe-type-tools/afdko#125]
If I use ProofPDF.py with the arguments charplot, digiplot, fontplot, fontsetplot or hintplot, I get an error in case of some fonts. (With the argument waterfall I don't get that error.):

```
Proofing font Input\Test.otf. Start time: Fri Apr 08 23:47:52 2016.

Processing 100 of 809 glyphs. Time remaining:  0 min 2 sec
Processing 200 of 809 glyphs. Time remaining:  0 min 2 sec
Traceback (most recent call last):
  File "C:\FDK_26.03.2016\Tools\SharedData\FDKScripts\ProofPDF.py", line 989, in
 <module>
    main()
  File "C:\FDK_26.03.2016\Tools\SharedData\FDKScripts\ProofPDF.py", line 981, in
 main
    proofMakePDF(params.rt_fileList, params, txPath)
  File "C:\FDK_26.03.2016\Tools\SharedData\FDKScripts\ProofPDF.py", line 931, in
 proofMakePDF
    pdfFilePath = makePDF(pdfFont,  params)
  File "C:\FDK_26.03.2016\Tools\SharedData\FDKScripts\fontPDF.py", line 1648, in
 makePDF
    makeProofPDF(pdfFont, params, progressBarInstance)
  File "C:\FDK_26.03.2016\Tools\SharedData\FDKScripts\fontPDF.py", line 2264, in
 makeProofPDF
    pdfGlyph = pdfFont.getGlyph(params.rt_glyphList[gi])
  File "C:\FDK_26.03.2016\Tools\SharedData\FDKScripts\fontPDF.py", line 462, in
getGlyph
    return self.clientGetGlyph(glyphName)
  File "C:\FDK_26.03.2016\Tools\SharedData\FDKScripts\otfPDF.py", line 119, in c
lientGetGlyph
    return txPDFGlyph(self, glyphName)
  File "C:\FDK_26.03.2016\Tools\SharedData\FDKScripts\fontPDF.py", line 588, in
__init__
    self.clientInitData()
  File "C:\FDK_26.03.2016\Tools\SharedData\FDKScripts\otfPDF.py", line 326, in c
lientInitData
    drawCharString(charstring, pen)
  File "C:\FDK_26.03.2016\Tools\SharedData\FDKScripts\otfPDF.py", line 299, in d
rawCharString
    extractor.execute(charString)
  File "C:\FDK_26.03.2016\Tools\win\Python\AFDKOPython27\lib\site-packages\fontt
ools-3.0-py2.7.egg\fontTools\misc\psCharStrings.py", line 529, in execute
    rv = handler(index)
  File "C:\FDK_26.03.2016\Tools\win\Python\AFDKOPython27\lib\site-packages\fontt
ools-3.0-py2.7.egg\fontTools\misc\psCharStrings.py", line 744, in op_endchar
    self.pen.addComponent(baseGlyph, (1, 0, 0, 1, 0, 0))
  File "C:\FDK_26.03.2016\Tools\win\Python\AFDKOPython27\lib\site-packages\fontt
ools-3.0-py2.7.egg\fontTools\pens\basePen.py", line 195, in addComponent
    glyph = self.glyphSet[glyphName]
TypeError: 'NoneType' object has no attribute '__getitem__'
```

**Comment by miguelsousa** [comment]
The traceback happens when a T2 charstring contains a `seac` operator. Fix coming.
