### ISSUE TITLE
`otf2ttf` hangs on Windows if the system has 64 or more threads

### ISSUE THREAD

**Issue by be5invis** [adobe-type-tools/afdko#1420]
```
> otf2ttf .\SourceSerif4-Regular.otf
Exception in thread Thread-1:
Traceback (most recent call last):
  File "c:\program files\python39\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "c:\program files\python39\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "c:\program files\python39\lib\multiprocessing\pool.py", line 519, in _handle_workers
    cls._wait_for_updates(current_sentinels, change_notifier)
  File "c:\program files\python39\lib\multiprocessing\pool.py", line 499, in _wait_for_updates
    wait(sentinels, timeout=timeout)
  File "c:\program files\python39\lib\multiprocessing\connection.py", line 884, in wait
    ready_handles = _exhaustive_wait(waithandle_to_obj.keys(), timeout)
  File "c:\program files\python39\lib\multiprocessing\connection.py", line 816, in _exhaustive_wait
    res = _winapi.WaitForMultipleObjects(L, False, timeout)
ValueError: need at most 63 handles, got a sequence of length 66
```

The process hangs then, producing no TTF.

**Comment by josh-hadley** [comment]
@be5invis unfortunately we don't have a comparable system available to repro this or test a patch, so it's not likely we'll initiate a fix. If you want to take a try at something that gets it working for your setup, we'd love to review it and get it incorporated if applicable.

**Comment by be5invis** [comment]
Alternatively, do we have options to disable parallelism? If os then at least this problem can get workarounded.
