### ISSUE TITLE
Glyph causes `checkoutlinesufo` to enter into an infinite loop and never exit

### ISSUE THREAD

**Issue by ctrlcctrlv** [adobe-type-tools/afdko#1463]
# Graphical view of glyph causing the issue
![image](https://user-images.githubusercontent.com/838783/150791948-454e8c2b-ea45-412f-b027-370335c7372a.png)
![image](https://user-images.githubusercontent.com/838783/150792009-e7ec53a1-aa21-4b54-b35e-baabaa4c9138.png)
![image](https://user-images.githubusercontent.com/838783/150792039-1cf7ba3a-8b71-4ffa-ab74-ebe8843c7af8.png)

## Exploded
![image](https://user-images.githubusercontent.com/838783/150791694-da806995-ba24-4e82-aab9-cc1c801075d2.png)

# Command line

```sh
#!/bin/sh
/usr/bin/python /home/fred/.local/bin/checkoutlinesufo -q -e -d --min-area 10 -g cyr_EF.rlow --ignore-contour-order -w build/FRBAmericanCursive-Light.ufo
```

```
Checking outlines for cyr_EF.rlow:   0%|                                   | 0/1 [00:00<?, ?it/s]
```

# ``^C``

```python3-traceback
Traceback (most recent call last):
  File "/home/fred/.local/bin/checkoutlinesufo", line 8, in <module>
    sys.exit(main())
  File "/home/fred/.local/lib/python3.10/site-packages/afdko/checkoutlinesufo.py", line 1151, in main
    run(sys.argv[1:])
  File "/home/fred/.local/lib/python3.10/site-packages/afdko/checkoutlinesufo.py", line 1081, in run
    test(new_glyph, changed, msg, options)
  File "/home/fred/.local/lib/python3.10/site-packages/afdko/checkoutlinesufo.py", line 807, in do_overlap_removal
    new_glyph = new_glyph.removeOverlap()
  File "/home/fred/.local/lib/python3.10/site-packages/booleanOperations/booleanGlyph.py", line 251, in removeOverlap
    return self._booleanMath("union", None)
  File "/home/fred/.local/lib/python3.10/site-packages/booleanOperations/booleanGlyph.py", line 211, in _booleanMath
    func(contours, destination.getPointPen())
  File "/home/fred/.local/lib/python3.10/site-packages/booleanOperations/booleanOperationManager.py", line 100, in union
    return _performOperation("union", contours, [], outPen)
  File "/home/fred/.local/lib/python3.10/site-packages/booleanOperations/booleanOperationManager.py", line 89, in _performOperation
    outputContour.reCurveSubSegments(inputContours)
  File "/home/fred/.local/lib/python3.10/site-packages/booleanOperations/flatten.py", line 613, in reCurveSubSegments
    flatInputPoints = set(flatInputPointsSegmentDict.keys())
KeyboardInterrupt
```

# ``build/FRBAmericanCursive-Thin.ufo/glyphs/cyr_E_F_.rlow.glif``
Number of contours: 17

```xml
<?xml version="1.0" encoding="UTF-8"?>
<glyph name="cyr_EF.rlow" format="2">
  <advance width="585"/>
  <outline>
    <contour>
      <point x="196" y="541" type="curve"/>
      <point x="196" y="537.6863"/>
      <point x="198.6863" y="535"/>
      <point x="202" y="535" type="curve"/>
      <point x="202" y="535" type="line"/>
      <point x="270.33334" y="535"/>
      <point x="338.66666" y="535"/>
      <point x="407" y="535" type="curve"/>
      <point x="410.31372" y="535"/>
      <point x="413" y="537.6863"/>
      <point x="413" y="541" type="curve"/>
      <point x="413" y="544.3137"/>
      <point x="410.31372" y="547"/>
      <point x="407" y="547" type="curve"/>
      <point x="407" y="547" type="line"/>
      <point x="338.66666" y="547"/>
      <point x="270.33334" y="547"/>
      <point x="202" y="547" type="curve"/>
      <point x="198.6863" y="547"/>
      <point x="196" y="544.3137"/>
    </contour>
    <contour>
      <point x="412.78763" y="539.4178" type="curve"/>
      <point x="413.66147" y="542.6142"/>
      <point x="411.77866" y="545.91376"/>
      <point x="408.5822" y="546.7876" type="curve"/>
      <point x="405.3858" y="547.66144"/>
      <point x="402.0862" y="545.7786"/>
      <point x="401.21237" y="542.5822" type="curve"/>
      <point x="388.54572" y="496.2489"/>
      <point x="375.87906" y="449.91556"/>
      <point x="363.21237" y="403.5822" type="curve"/>
      <point x="362.33853" y="400.3858"/>
      <point x="364.22134" y="397.0862"/>
      <point x="367.4178" y="396.21237" type="curve"/>
      <point x="370.6142" y="395.33853"/>
      <point x="373.9138" y="397.22134"/>
      <point x="374.78763" y="400.4178" type="curve"/>
      <point x="374.78763" y="400.4178" type="line"/>
      <point x="387.45428" y="446.7511"/>
      <point x="400.12094" y="493.08444"/>
    </contour>
    <contour>
      <point x="370.62082" y="407.77692" type="curve"/>
      <point x="367.43033" y="408.6721"/>
      <point x="364.11823" y="406.81134"/>
      <point x="363.22308" y="403.62082" type="curve"/>
      <point x="363.22308" y="403.62082" type="line"/>
      <point x="337.5188" y="312.0061"/>
      <point x="306.58798" y="172"/>
      <point x="187" y="172" type="curve"/>
      <point x="183.6863" y="172"/>
      <point x="181" y="169.3137"/>
      <point x="181" y="166" type="curve"/>
      <point x="181" y="162.6863"/>
      <point x="183.6863" y="160"/>
      <point x="187" y="160" type="curve"/>
      <point x="314.0606" y="160"/>
      <point x="347.27875" y="302.37057"/>
      <point x="374.77692" y="400.37918" type="curve"/>
      <point x="375.6721" y="403.56967"/>
      <point x="373.81134" y="406.88177"/>
    </contour>
    <contour>
      <point x="187" y="160" type="curve"/>
      <point x="190.3137" y="160"/>
      <point x="193" y="162.6863"/>
      <point x="193" y="166" type="curve"/>
      <point x="193" y="169.3137"/>
      <point x="190.3137" y="172"/>
      <point x="187" y="172" type="curve"/>
      <point x="127.75838" y="172"/>
      <point x="72.0486" y="216.029"/>
      <point x="72.0486" y="278" type="curve"/>
      <point x="72.0486" y="281.31372"/>
      <point x="69.362305" y="284"/>
      <point x="66.0486" y="284" type="curve"/>
      <point x="62.73489" y="284"/>
      <point x="60.0486" y="281.31372"/>
      <point x="60.0486" y="278" type="curve"/>
      <point x="60.0486" y="209.39537"/>
      <point x="121.13648" y="160"/>
    </contour>
    <contour>
      <point x="60.0486" y="278" type="curve"/>
      <point x="60.0486" y="274.68628"/>
      <point x="62.73489" y="272"/>
      <point x="66.0486" y="272" type="curve"/>
      <point x="69.362305" y="272"/>
      <point x="72.0486" y="274.68628"/>
      <point x="72.0486" y="278" type="curve"/>
      <point x="72.0486" y="358.7029"/>
      <point x="152.02979" y="430"/>
      <point x="231" y="430" type="curve"/>
      <point x="234.3137" y="430"/>
      <point x="237" y="432.68628"/>
      <point x="237" y="436" type="curve"/>
      <point x="237" y="439.31372"/>
      <point x="234.3137" y="442"/>
      <point x="231" y="442" type="curve"/>
      <point x="231" y="442" type="line"/>
      <point x="145.4236" y="442"/>
      <point x="60.0486" y="365.3189"/>
    </contour>
    <contour>
      <point x="225" y="436" type="curve"/>
      <point x="225" y="432.68628"/>
      <point x="227.6863" y="430"/>
      <point x="231" y="430" type="curve"/>
      <point x="231" y="430" type="line"/>
      <point x="284.08316" y="430"/>
      <point x="336.524" y="390.05392"/>
      <point x="336.524" y="334" type="curve"/>
      <point x="336.524" y="330.68628"/>
      <point x="339.21027" y="328"/>
      <point x="342.524" y="328" type="curve"/>
      <point x="345.8377" y="328"/>
      <point x="348.524" y="330.68628"/>
      <point x="348.524" y="334" type="curve"/>
      <point x="348.524" y="334" type="line"/>
      <point x="348.524" y="396.6924"/>
      <point x="290.7177" y="442"/>
      <point x="231" y="442" type="curve"/>
      <point x="227.6863" y="442"/>
      <point x="225" y="439.31372"/>
    </contour>
    <contour>
      <point x="342.524" y="340" type="curve"/>
      <point x="339.21027" y="340"/>
      <point x="336.524" y="337.31372"/>
      <point x="336.524" y="334" type="curve"/>
      <point x="336.524" y="334" type="line"/>
      <point x="336.524" y="307.86194"/>
      <point x="324.88098" y="282.39243"/>
      <point x="324.88098" y="256" type="curve"/>
      <point x="324.88098" y="252.6863"/>
      <point x="327.56726" y="250"/>
      <point x="330.88098" y="250" type="curve"/>
      <point x="334.1947" y="250"/>
      <point x="336.88098" y="252.6863"/>
      <point x="336.88098" y="256" type="curve"/>
      <point x="336.88098" y="256" type="line"/>
      <point x="336.88098" y="282.3078"/>
      <point x="348.524" y="307.75806"/>
      <point x="348.524" y="334" type="curve"/>
      <point x="348.524" y="337.31372"/>
      <point x="345.8377" y="340"/>
    </contour>
    <contour>
      <point x="336.88098" y="256" type="curve"/>
      <point x="336.88098" y="259.31372"/>
      <point x="334.1947" y="262"/>
      <point x="330.88098" y="262" type="curve"/>
      <point x="327.56726" y="262"/>
      <point x="324.88098" y="259.31372"/>
      <point x="324.88098" y="256" type="curve"/>
      <point x="324.88098" y="187.29099"/>
      <point x="373.23764" y="163.96797"/>
      <point x="435.10016" y="165.00084" type="curve"/>
      <point x="438.41342" y="165.05615"/>
      <point x="441.05447" y="167.78691"/>
      <point x="440.99918" y="171.10016" type="curve"/>
      <point x="440.94385" y="174.4134"/>
      <point x="438.21307" y="177.05449"/>
      <point x="434.89984" y="176.99916" type="curve"/>
      <point x="379.79193" y="176.07907"/>
      <point x="336.88098" y="194.28903"/>
    </contour>
    <contour>
      <point x="429.0004" y="171.06902" type="curve"/>
      <point x="428.96228" y="167.75552"/>
      <point x="431.6175" y="165.03851"/>
      <point x="434.93097" y="165.0004" type="curve"/>
      <point x="434.93097" y="165.0004" type="line"/>
      <point x="527.9285" y="163.93054"/>
      <point x="608.522" y="229.66783"/>
      <point x="608.522" y="326" type="curve"/>
      <point x="608.522" y="329.31372"/>
      <point x="605.8357" y="332"/>
      <point x="602.522" y="332" type="curve"/>
      <point x="599.20825" y="332"/>
      <point x="596.522" y="329.31372"/>
      <point x="596.522" y="326" type="curve"/>
      <point x="596.522" y="326" type="line"/>
      <point x="596.522" y="236.35657"/>
      <point x="521.40826" y="176.00635"/>
      <point x="435.06903" y="176.9996" type="curve"/>
      <point x="431.75552" y="177.03772"/>
      <point x="429.0385" y="174.3825"/>
    </contour>
    <contour>
      <point x="602.522" y="320" type="curve"/>
      <point x="605.8357" y="320"/>
      <point x="608.522" y="322.68628"/>
      <point x="608.522" y="326" type="curve"/>
      <point x="608.522" y="326" type="line"/>
      <point x="608.522" y="389.73578"/>
      <point x="562.12744" y="442"/>
      <point x="497" y="442" type="curve"/>
      <point x="493.68628" y="442"/>
      <point x="491" y="439.31372"/>
      <point x="491" y="436" type="curve"/>
      <point x="491" y="432.68628"/>
      <point x="493.68628" y="430"/>
      <point x="497" y="430" type="curve"/>
      <point x="497" y="430" type="line"/>
      <point x="555.5102" y="430"/>
      <point x="596.522" y="383.1442"/>
      <point x="596.522" y="326" type="curve"/>
      <point x="596.522" y="322.68628"/>
      <point x="599.20825" y="320"/>
    </contour>
    <contour>
      <point x="503" y="436" type="curve"/>
      <point x="503" y="439.31372"/>
      <point x="500.31372" y="442"/>
      <point x="497" y="442" type="curve"/>
      <point x="497" y="442" type="line"/>
      <point x="431.50876" y="442"/>
      <point x="371.88443" y="391.6067"/>
      <point x="342.6805" y="335.63257" type="curve"/>
      <point x="341.1477" y="332.6947"/>
      <point x="342.28674" y="329.07047"/>
      <point x="345.22464" y="327.53766" type="curve"/>
      <point x="348.1625" y="326.00485"/>
      <point x="351.78674" y="327.1439"/>
      <point x="353.31955" y="330.0818" type="curve"/>
      <point x="353.31955" y="330.0818" type="line"/>
      <point x="380.42133" y="382.02682"/>
      <point x="436.07574" y="430"/>
      <point x="497" y="430" type="curve"/>
      <point x="500.31372" y="430"/>
      <point x="503" y="432.68628"/>
    </contour>
    <contour>
      <point x="349.63773" y="338.62936" type="curve"/>
      <point x="346.44983" y="339.5338"/>
      <point x="343.13232" y="337.68274"/>
      <point x="342.22784" y="334.49487" type="curve"/>
      <point x="342.22784" y="334.49487" type="line"/>
      <point x="324.7993" y="273.06628"/>
      <point x="307.3707" y="211.63771"/>
      <point x="289.9421" y="150.20912" type="curve"/>
      <point x="289.03766" y="147.02124"/>
      <point x="290.88873" y="143.70374"/>
      <point x="294.0766" y="142.79927" type="curve"/>
      <point x="297.2645" y="141.8948"/>
      <point x="300.582" y="143.74586"/>
      <point x="301.48648" y="146.93376" type="curve"/>
      <point x="318.91504" y="208.36234"/>
      <point x="336.34363" y="269.79092"/>
      <point x="353.77222" y="331.21948" type="curve"/>
      <point x="354.67667" y="334.40738"/>
      <point x="352.8256" y="337.72488"/>
    </contour>
    <contour>
      <point x="301.4064" y="146.67407" type="curve"/>
      <point x="302.45428" y="149.81773"/>
      <point x="300.7553" y="153.21565"/>
      <point x="297.61166" y="154.26353" type="curve"/>
      <point x="294.468" y="155.31143"/>
      <point x="291.07007" y="153.61247"/>
      <point x="290.0222" y="150.46881" type="curve"/>
      <point x="267.86038" y="83.983376"/>
      <point x="235.38306" y="6"/>
      <point x="154" y="6" type="curve"/>
      <point x="150.6863" y="6"/>
      <point x="148" y="3.3137085"/>
      <point x="148" y="-0.0000000000000045942826" type="curve"/>
      <point x="148" y="-3.3137085"/>
      <point x="150.6863" y="-6"/>
      <point x="154" y="-6" type="curve"/>
      <point x="241.53477" y="-6"/>
      <point x="277.3845" y="74.60838"/>
    </contour>
    <contour>
      <point x="154" y="-6" type="curve"/>
      <point x="157.3137" y="-6"/>
      <point x="160" y="-3.3137085"/>
      <point x="160" y="-0.000000000000006798647" type="curve"/>
      <point x="160" y="3.3137085"/>
      <point x="157.3137" y="6"/>
      <point x="154" y="6" type="curve"/>
      <point x="107.496445" y="6"/>
      <point x="33.771233" y="31.413342"/>
      <point x="15.607542" y="79.13435" type="curve"/>
      <point x="14.428769" y="82.231316"/>
      <point x="10.962604" y="83.786316"/>
      <point x="7.8656435" y="82.607544" type="curve"/>
      <point x="4.768684" y="81.42877"/>
      <point x="3.213686" y="77.9626"/>
      <point x="4.3924584" y="74.86565" type="curve"/>
      <point x="24.44781" y="22.174717"/>
      <point x="102.24726" y="-6"/>
    </contour>
    <contour>
      <point x="15.67015" y="78.96199" type="curve"/>
      <point x="14.586574" y="82.09353"/>
      <point x="11.169549" y="83.75372"/>
      <point x="8.038012" y="82.67015" type="curve"/>
      <point x="4.906474" y="81.58657"/>
      <point x="3.2462738" y="78.16955"/>
      <point x="4.32985" y="75.03801" type="curve"/>
      <point x="22.968664" y="21.171806"/>
      <point x="102.44039" y="-6"/>
      <point x="154" y="-6" type="curve"/>
      <point x="157.3137" y="-6"/>
      <point x="160" y="-3.3137085"/>
      <point x="160" y="-0.0000000000000014695761" type="curve"/>
      <point x="160" y="3.3137085"/>
      <point x="157.3137" y="6"/>
      <point x="154" y="6" type="curve"/>
      <point x="154" y="6" type="line"/>
      <point x="107.897285" y="6"/>
      <point x="32.49413" y="30.340658"/>
    </contour>
    <contour>
      <point x="148" y="0.00000000000000073478806" type="curve"/>
      <point x="148" y="-3.3137085"/>
      <point x="150.6863" y="-6"/>
      <point x="154" y="-6" type="curve"/>
      <point x="154" y="-6" type="line"/>
      <point x="241.19366" y="-6"/>
      <point x="334.06808" y="-7.917701"/>
      <point x="420.23196" y="6.6641808" type="curve"/>
      <point x="423.49924" y="7.2171116"/>
      <point x="425.69962" y="10.313981"/>
      <point x="425.1467" y="13.581233" type="curve"/>
      <point x="424.59375" y="16.848484"/>
      <point x="421.4969" y="19.048876"/>
      <point x="418.22964" y="18.495945" type="curve"/>
      <point x="418.22964" y="18.495945" type="line"/>
      <point x="332.74493" y="4.0290036"/>
      <point x="240.50586" y="6"/>
      <point x="154" y="6" type="curve"/>
      <point x="150.6863" y="6"/>
      <point x="148" y="3.3137085"/>
    </contour>
    <contour>
      <point x="413.3184" y="11.558702" type="curve"/>
      <point x="413.88245" y="8.293358"/>
      <point x="416.98682" y="6.1035514"/>
      <point x="420.25217" y="6.6676335" type="curve"/>
      <point x="420.25217" y="6.6676335" type="line"/>
      <point x="475.78275" y="16.260433"/>
      <point x="541.84247" y="39.45619"/>
      <point x="588.44147" y="72.08508" type="curve"/>
      <point x="591.1559" y="73.98575"/>
      <point x="591.81555" y="77.72702"/>
      <point x="589.9149" y="80.44145" type="curve"/>
      <point x="588.0142" y="83.15588"/>
      <point x="584.27295" y="83.815575"/>
      <point x="581.55853" y="81.91492" type="curve"/>
      <point x="581.55853" y="81.91492" type="line"/>
      <point x="536.4098" y="50.301476"/>
      <point x="472.0023" y="27.785103"/>
      <point x="418.20944" y="18.492493" type="curve"/>
      <point x="414.9441" y="17.92841"/>
      <point x="412.7543" y="14.824047"/>
    </contour>
  </outline>
</glyph>
```

# More info
* .glif is valid
* Skia also struggles? (this is with @MatthewBlanchard's [patch №497140](https://skia-review.googlesource.com/c/skia/+/497140))
    ```sh
    MFEKpathops BOOLEAN -p union -i build/FRBAmericanCursive-Thin.ufo/glyphs/cyr_E_F_.rlow.glif -o /tmp/skia_cyr_E_F_.rlow.glif
    ```
    * ![image](https://user-images.githubusercontent.com/838783/150793263-cc308da1-365d-44ea-9089-77430329028a.png)
* @Logicalshift `flo_curves` doesn't, but struggles with other examples.
    ```sh
    MFEKpathops BOOLEAN -p remove_interior -i build/FRBAmericanCursive-Thin.ufo/glyphs/cyr_E_F_.rlow.glif -o /tmp/flo_cyr_E_F_.rlow.glif
    ```
    * ![image](https://user-images.githubusercontent.com/838783/150793776-cd027f86-4af3-4c00-bf31-588e911e18cf.png)

**Why are boolean operations so hard??**

**Comment by frankrolf** [comment]
While this .glif is technically valid, it is a very unusual example – it contains many overlapping points, sometimes up to 4 at a time.

While I am not doubting there might be an issue with `checkoutlinesufo` (which uses Skia if I’m not mistaken), this glyph needs some care. Something like this will never lead to a satisfying result:
![image](https://user-images.githubusercontent.com/2049645/150813789-ef299a17-64c4-4d27-b2b2-7c76bb540c62.png)

The contours seem to have been created by expanding individual skeletal segments – could there be a workflow where the whole contour is expanded, w/o relying on the segment-by-segment approach (read: maybe the issue happens earlier in the toolchain).

**Comment by ctrlcctrlv** [comment]
my .glif is valid, so i'd "never say never". i prefer to expand segmentwise, it leads to the lowest number of bugs in the contour expansion, which is another bug-prone component.

**Comment by skef** [comment]
We're not going to investigate this problem further.
