### ISSUE TITLE
[comparefamily]  doFamilyTest18 should skip rest of tests if there are no bluezones

### ISSUE THREAD

**Issue by colinmford** [adobe-type-tools/afdko#1593]
I accidentally ran a font through comparefamily without any blue zones. It correctly prints the error on Line 4093:
https://github.com/adobe-type-tools/afdko/blob/feebd77d9b6507a0b32f837535511be3c94d9c6f/python/afdko/comparefamily.py#L4091-L4095

but then continues on to line 4104, which tries to take an index of an empty list.

```
Traceback (most recent call last):
  File "/Users/colinmford/MyFont/.venv/bin/compareFamily", line 8, in <module>
    sys.exit(main())
  File "/Users/colinmford/MyFont/.venv/lib/python3.10/site-packages/afdko/comparefamily.py", line 5028, in main
    doFamilyTests(singleTestList, familyTestList)
  File "/Users/colinmford/MyFont/.venv/lib/python3.10/site-packages/afdko/comparefamily.py", line 4377, in doFamilyTests
    doFamilyTest18()
  File "/Users/colinmford/MyFont/.venv/lib/python3.10/site-packages/afdko/comparefamily.py", line 4104, in doFamilyTest18
    if tempBlues[1] < font.fontBBox[1]:
IndexError: list index out of range
```

https://github.com/adobe-type-tools/afdko/blob/feebd77d9b6507a0b32f837535511be3c94d9c6f/python/afdko/comparefamily.py#L4104-L4105

The function should probably be restructured around line 4101 to not continue if any of the tests above it (no zones, zones with values of zero, more than 14 zones, or an odd number of zones) fail.

**Comment by colinmford** [comment]
Took the liberty of making PR #1599, looking forward to your review!

**Comment by colinmford** [comment]
I would like to fix this error, if possible — @frankrolf or @josh-hadley, could you take a look at PR #1599 when you have a minute?

**Comment by skef** [comment]
This should be fixed by the associated pr
