### ISSUE TITLE
[otfstemhist] – barfs w/o any arguments

### ISSUE THREAD

**Issue by frankrolf** [adobe-type-tools/afdko#1697]
`otfstemhist` assumes a law-abiding user, who always passes input files as arguments.

However, my first use of the tool (command `otfstemhist` only) resulted in
```
Traceback (most recent call last):
  File "/Users/fg/.pyenv/versions/3.10.13/bin/otfstemhist", line 8, in <module>
    sys.exit(stemhist())
  File "/Users/fg/.pyenv/versions/3.10.13/lib/python3.10/site-packages/afdko/otfautohint/__main__.py", line 935, in stemhist
    options, pargs = get_stemhist_options(args)
  File "/Users/fg/.pyenv/versions/3.10.13/lib/python3.10/site-packages/afdko/otfautohint/__main__.py", line 927, in get_stemhist_options
    options.font_format = _validate_font_paths(parsed_args.font_paths, parser)
  File "/Users/fg/.pyenv/versions/3.10.13/lib/python3.10/site-packages/afdko/otfautohint/__main__.py", line 457, in _validate_font_paths
    ft_format_str, = format_set
ValueError: not enough values to unpack (expected 1, got 0)
```

Normally, any tool set up with `argparse` should now print the help, instead of doing anything.

I solved this by adding two if-loops and a `print_help()` statement to the parser (around line 930):
``` py
    options = ReportOptions(parsed_args)

    if parsed_args.font_paths:
        options.font_format = _validate_font_paths(parsed_args.font_paths, parser)

        handle_glyph_lists(options, parsed_args)

        return options, parsed_args
    else:
        parser.print_help()
        return None, None


def stemhist(args=None):
    options, pargs = get_stemhist_options(args)

    if options and pargs:
        try:
            hintFiles(options)
        except Exception as ex:
            if pargs.traceback:
                raise
            logging.error(ex)
            return 1


if __name__ == '__main__':
    sys.exit(main())

```

**Comment by skef** [comment]
Yeah, this is just a bug, some structural difference between the `otfautohint` and `otfstemhist` paths. I'll fix it.
