### ISSUE TITLE
[ttxn] ClassRecord AttributeError

### ISSUE THREAD

**Issue by erniemarch** [adobe-type-tools/afdko#350]
```python
ERROR: Unhandled exception has occurred
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/afdko/Tools/SharedData/FDKScripts/ttxn.py", line 2347, in run
    supressHints, supressVersions, supressTTFDiffs)
  File "/usr/local/lib/python2.7/site-packages/fontTools/misc/loggingTools.py", line 372, in wrapper
    return func(*args, **kwds)
  File "/usr/local/lib/python2.7/site-packages/afdko/Tools/SharedData/FDKScripts/ttxn.py", line 2293, in ttnDump
    bitmapGlyphDataFormat=options.bitmapGlyphDataFormat)
  File "/usr/local/lib/python2.7/site-packages/fontTools/ttLib/ttFont.py", line 221, in saveXML
    self._saveXML(writer, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/fontTools/ttLib/ttFont.py", line 276, in _saveXML
    self._tableToXML(tableWriter, tag, splitGlyphs=splitGlyphs)
  File "/usr/local/lib/python2.7/site-packages/afdko/Tools/SharedData/FDKScripts/ttxn.py", line 2065, in _tableToXML
    dumpOTLAsFeatureFile(tag, writer, self)
  File "/usr/local/lib/python2.7/site-packages/afdko/Tools/SharedData/FDKScripts/ttxn.py", line 2021, in dumpOTLAsFeatureFile
    otlConverter.otlFeatureFormat(writer)
  File "/usr/local/lib/python2.7/site-packages/afdko/Tools/SharedData/FDKScripts/ttxn.py", line 1617, in otlFeatureFormat
    self.buildClasses()
  File "/usr/local/lib/python2.7/site-packages/afdko/Tools/SharedData/FDKScripts/ttxn.py", line 1741, in buildClasses
    classRec.classIndex, classRec.type)
AttributeError: ClassRecord instance has no attribute 'type'
```

**Comment by cjchapman** [comment]
Fixed by PR https://github.com/adobe-type-tools/afdko/pull/358
