### ISSUE TITLE
ttxn error

### ISSUE THREAD

**Issue by weiweihuanghuang** [adobe-type-tools/afdko#40]
```
Traceback (most recent call last):
  File "/usr/local/bin/FDK/Tools/osx/../SharedData/FDKScripts/ttxn.py", line 2308, in <module>
    run(sys.argv[1:])
  File "/usr/local/bin/FDK/Tools/osx/../SharedData/FDKScripts/ttxn.py", line 2300, in run
    ttf = ttnDump(input, output, options, showExtensionFlag, supressHints, supressVersions, supressTTFDiffs)
  File "/usr/local/bin/FDK/Tools/osx/../SharedData/FDKScripts/ttxn.py", line 2211, in ttnDump
    disassembleInstructions=options.disassembleInstructions)
  File "/usr/local/bin/FDK/Tools/osx/Python/Current/lib/python2.7/site-packages/FontTools/fontTools/ttLib/__init__.py", line 281, in saveXML
    self._tableToXML(tableWriter, tag, progress, quiet)
  File "/usr/local/bin/FDK/Tools/osx/../SharedData/FDKScripts/ttxn.py", line 1983, in _tableToXML
    dumpOTLAsFeatureFile(tag, ttxnWriter, self)
  File "/usr/local/bin/FDK/Tools/osx/../SharedData/FDKScripts/ttxn.py", line 1916, in dumpOTLAsFeatureFile
    otlConverter.otlFeatureFormat(writer)
  File "/usr/local/bin/FDK/Tools/osx/../SharedData/FDKScripts/ttxn.py", line 1537, in otlFeatureFormat
    self.buildClasses()
  File "/usr/local/bin/FDK/Tools/osx/../SharedData/FDKScripts/ttxn.py", line 1626, in buildClasses
    handler = self.classHandlers.get( (lookup.LookupType, subtable.Format), None)
  File "/usr/local/bin/FDK/Tools/osx/Python/Current/lib/python2.7/site-packages/FontTools/fontTools/ttLib/tables/otBase.py", line 531, in __getattr__
    raise AttributeError(attr)
AttributeError: Format
```

**Comment by readroberts** [comment]
I think you are using an older version of ttxn.py,  with a recent version of the GitHub FontTools  Python module. In the  current version , the 'buildClasses()' function starts at line 1617, the call to self.classHandlers.get() is at line 1631, and looks like:
				handler = self.classHandlers.get( (lookup.LookupType, format), None)

I had to make changes in this function when building the latest public FDK release, as the FontTools changed so that the earlier version did not work, in exactly the way that you report.

Please the download the latest FDK, and run the 'FinishInstallOSX' script.

**Comment by weiweihuanghuang** [comment]
Solved it! Thanks

**Comment by behdad** [comment]
@readroberts Humm, is that something I need to fix in fonttools?  I don't fully understand.  What did you have to change?  Thanks.

**Comment by readroberts** [comment]
This is a bug in the FDK program ttxn, not in fontTools.  ttxn reaches deep into the fontTools internals, and was using an object attribute that was removed sometime in the last several years. The latest FDK release is now up to date with the current version of fontTools.

**Comment by behdad** [comment]
Thanks Read.
