### ISSUE TITLE
Set Windows CMD codepage to UTF-8 will cause MakeOTF.py error

### ISSUE THREAD

**Issue by LIXiangChen** [adobe-type-tools/afdko#513]
This command can set the codepage of the CMD to UTF-8:

```
> chcp 65001
```

However, when run `makeotf`, an error will be thrown:

```
 Traceback (most recent call last):
  File "c:\python27\lib\site-packages\afdko\Tools\SharedData\FDKScripts\MakeOTF.py", line 3060, in main
    runMakeOTF(makeOTFParams)
  File "c:\python27\lib\site-packages\afdko\Tools\SharedData\FDKScripts\MakeOTF.py", line 3010, in runMakeOTF
    outputPath, match.group(1)))
LookupError: unknown encoding: cp65001
```

**Comment by anthrotype** [comment]
that codepage is not an exact match for utf-8 and is not supported by python.
don't use that. Use python3.6 or above which don't have issues with the windows console encoding, unlike python2.7.

**Comment by anthrotype** [comment]
oh forgot afdko is py2.7 only..
then I recommend you install https://github.com/Drekin/win-unicode-console
instead of changing your console codepage.
