### ISSUE TITLE
[checkoutlinesufo] cannot add new overlap

### ISSUE THREAD

**Issue by frankrolf** [adobe-type-tools/afdko#674]
I am running checkOutlinesUFO 2.2.1 (which I just got through updating the FDK via pip).
Any time I add a new overlap to my UFO file, checkoutlines fails with the following message:

```
Traceback (most recent call last):
  File "/usr/local/bin/checkOutlinesUFO", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/afdko/checkoutlinesufo.py", line 1137, in main
    run(sys.argv[1:])
  File "/usr/local/lib/python3.6/site-packages/afdko/checkoutlinesufo.py", line 1119, in run
    ufotools.validateLayers(font_path, False)
  File "/usr/local/lib/python3.6/site-packages/afdko/ufotools.py", line 2482, in validateLayers
    cleanupContentsList(glyphDirPath, doWarning)
  File "/usr/local/lib/python3.6/site-packages/afdko/ufotools.py", line 2432, in cleanupContentsList
    for glyphName, fileName in itemList:
RuntimeError: dictionary changed size during iteration
```

I think this is the culprit in ufoTools – Python 3 no longer just returns a list for contentsDict.items(), but a reference to the actual dictionary. :
```
    itemList = contentsDict.items()
    for glyphName, fileName in itemList:
        if fileName not in fileDict:
            del contentsDict[glyphName]
```

I suspect the fix would be 

```
    itemList = list(contentsDict.items())
    for glyphName, fileName in itemList:
        if fileName not in fileDict:
            del contentsDict[glyphName]
```

Unfortunately I cannot test it here because installing the FDK from source doesn’t work for me. I can open another issue for this, but it may have to do with my local configuration.

**Comment by miguelsousa** [comment]
Fixed via #676
