### ISSUE TITLE
Cannot install from source using Python3

### ISSUE THREAD

**Issue by frankrolf** [adobe-type-tools/afdko#675]
I solved my problem mentioned in #674 (by running the setup.py file using Python 2).
Not sure this is relevant, but Python 3 does not allow installing through setup.py:

```
Traceback (most recent call last):
  File "setup.py", line 274, in <module>
    main()
  File "setup.py", line 268, in main
    'install': InstallPlatlib,
  File "/usr/local/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.6/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/usr/local/lib/python3.6/site-packages/setuptools/command/install.py", line 117, in do_egg_install
    cmd.run()
  File "/usr/local/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 412, in run
    self.easy_install(spec, not self.no_deps)
  File "/usr/local/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 654, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/usr/local/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 701, in install_item
    self.process_distribution(spec, dist, deps)
  File "/usr/local/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 726, in process_distribution
    self.install_egg_scripts(dist)
  File "/usr/local/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 600, in install_egg_scripts
    dist.get_metadata('scripts/' + script_name)
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1405, in get_metadata
    return value.decode('utf-8') if six.PY3 else value
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcf in position 0: invalid continuation byte
```

**Comment by cjchapman** [comment]
Try this:
```python
python3 setup.py bdist_wheel
pip3 install dist/*.whl
```

**Comment by frankrolf** [comment]
Thank you @cjchapman. Is this information that should make it into the readme file?

**Comment by cjchapman** [comment]
@frankrolf Yes.

**Comment by anthrotype** [comment]
@cjchapman correct.

also see my lengthy explanation https://github.com/adobe-type-tools/afdko/pull/677#issuecomment-436747212
