### ISSUE TITLE
[makeotf] verbose error message

### ISSUE THREAD

**Issue by frankrolf** [adobe-type-tools/afdko#759]
A faulty line of feature code (missing `sub`):
```
feature liga {
    f f by f_f;
 } liga;
```
 triggered this long error message for a student today:
```
syntax error at "f" missing { feature script language subtable lookup lookupflag enumerate except ignore substitute reverse position parameters feat_names cv_params sizemenuname markClass GCLASS ";" "}" } [./../../family.fea 21]
```
I wonder if it could be optimized?

**Comment by miguelsousa** [comment]
I honestly don't see a lot of room for improvement. The FEA parser is expecting a keyword at the beginning of the line, and the missing token can be any of the ones listed.

Out of curiosity, I ran that FEA code thru **feaLib** (using this command line: `fonttools feaLib family.fea myfont.otf`) and the error message looked like this:
```
Traceback (most recent call last):
  File "/Users/msousa/Tools/afdko-live3/bin/fonttools", line 10, in <module>
    sys.exit(main())
  File "/Users/msousa/Tools/afdko-live3/lib/python3.7/site-packages/fontTools/__main__.py", line 29, in main
    runpy.run_module(mod, run_name='__main__')
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 208, in run_module
    return _run_code(code, {}, init_globals, run_name, mod_spec)
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/msousa/Tools/afdko-live3/lib/python3.7/site-packages/fontTools/feaLib/__main__.py", line 45, in <module>
    sys.exit(main())
  File "/Users/msousa/Tools/afdko-live3/lib/python3.7/site-packages/fontTools/feaLib/__main__.py", line 40, in main
    addOpenTypeFeatures(font, options.input_fea, tables=options.tables)
  File "/Users/msousa/Tools/afdko-live3/lib/python3.7/site-packages/fontTools/feaLib/builder.py", line 22, in addOpenTypeFeatures
    builder.build(tables=tables)
  File "/Users/msousa/Tools/afdko-live3/lib/python3.7/site-packages/fontTools/feaLib/builder.py", line 108, in build
    self.parseTree = Parser(self.file, self.glyphMap).parse()
  File "/Users/msousa/Tools/afdko-live3/lib/python3.7/site-packages/fontTools/feaLib/parser.py", line 75, in parse
    statements.append(self.parse_feature_block_())
  File "/Users/msousa/Tools/afdko-live3/lib/python3.7/site-packages/fontTools/feaLib/parser.py", line 1239, in parse_feature_block_
    cv_feature)
  File "/Users/msousa/Tools/afdko-live3/lib/python3.7/site-packages/fontTools/feaLib/parser.py", line 1421, in parse_block_
    self.cur_token_location_)
fontTools.feaLib.error.FeatureLibError: /Users/msousa/Desktop/family.fea:2:5: Expected glyph class definition or statement: got NAME f
```

**Comment by frankrolf** [comment]
Yep. I was just wondering, but it’s admittedly a low-priority problem.
