### ISSUE TITLE
bug356.otf is rejected by OTS/can’t be dumped by FontTools

### ISSUE THREAD

**Issue by khaledhosny** [adobe-type-tools/afdko#895]
The font [`tests/tx_data/input/bug356.otf`](https://github.com/adobe-type-tools/afdko/blob/develop/tests/tx_data/input/bug356.otf) is rejectd by OTS and gives the follwing error with FontTools:

```
ERROR: Error in charstring 3
ERROR: Unhandled exception has occurred
Traceback (most recent call last):
  File "/fonttools/Lib/fontTools/ttx.py", line 400, in main
    process(jobs, options)
  File "/fonttools/Lib/fontTools/ttx.py", line 374, in process
    action(input, output, options)
  File "/fonttools/Lib/fontTools/misc/loggingTools.py", line 374, in wrapper
    return func(*args, **kwds)
  File "/fonttools/Lib/fontTools/ttx.py", line 271, in ttDump
    newlinestr=options.newlinestr)
  File "/fonttools/Lib/fontTools/ttLib/ttFont.py", line 227, in saveXML
    self._saveXML(writer, **kwargs)
  File "/fonttools/Lib/fontTools/ttLib/ttFont.py", line 282, in _saveXML
    self._tableToXML(tableWriter, tag, splitGlyphs=splitGlyphs)
  File "/fonttools/Lib/fontTools/ttLib/ttFont.py", line 313, in _tableToXML
    table.toXML(writer, self)
  File "/fonttools/Lib/fontTools/ttLib/tables/C_F_F_.py", line 41, in toXML
    self.cff.toXML(writer)
  File "/fonttools/Lib/fontTools/cffLib/__init__.py", line 155, in toXML
    font.toXML(xmlWriter)
  File "/fonttools/Lib/fontTools/cffLib/__init__.py", line 2382, in toXML
    self.decompileAllCharStrings()
  File "/fonttools/Lib/fontTools/cffLib/__init__.py", line 2396, in decompileAllCharStrings
    charString.decompile()
  File "/fonttools/Lib/fontTools/misc/psCharStrings.py", line 974, in decompile
    decompiler.execute(self)
  File "/fonttools/Lib/fontTools/misc/psCharStrings.py", line 290, in execute
    token, isOperator, index = charString.getToken(index)
  File "/fonttools/Lib/fontTools/misc/psCharStrings.py", line 1053, in getToken
    token, index = handler(self, b0, self.bytecode, index)
  File "/fonttools/Lib/fontTools/misc/psCharStrings.py", line 36, in read_smallInt2
    b1 = byteord(data[index])
IndexError: index out of range
```

The CharString 3 seems to be one byte too short (the last byte is 251, so there should be another byte after it). I’m not sure if the font is broken or there is a bug in both tools.

**Comment by khaledhosny** [comment]
`tx -dcf` dumps the font fine and shows a -108 and the end of that CharString, is it just assuming the second (missing) byte is 0?

**Comment by khaledhosny** [comment]
I’m not very familiar with `cffread` code, but the relevant part calls `read1()`, to get the second byte:
https://github.com/adobe-type-tools/afdko/blob/9afe2436328d668569b26c9b58742049e09bf81e/c/public/lib/source/cffread/cffread.c#L1488-L1495

which seems to call `nextbuf()` when the end of the current buffer is reached, and I’m not sure if this is the right thing to do.
https://github.com/adobe-type-tools/afdko/blob/9afe2436328d668569b26c9b58742049e09bf81e/c/public/lib/source/cffread/cffread.c#L495-L497

**Comment by miguelsousa** [comment]
Related to https://github.com/fonttools/fonttools/issues/1474

**Comment by miguelsousa** [comment]
and #860
